(define (element-of-set? x set)
  (cond ((null? set) false)
        ((= x (car set)) true)
        ((< x (car set)) false)
        (else (element-of-set? x (cdr set)))))

(define (intersection-set set1 set2)
  (if (or (null? set1) (null? set2))
      '()
      (let ((x1 (car set1)) (x2 (car set2)))
        (cond ((= x1 x2)
               (cons x1
                     (intersection-set (cdr set1)
                                       (cdr set2))))
              ((< x1 x2)
               (intersection-set (cdr set1) set2))
              ((< x2 x1)
               (intersection-set set1 (cdr set2)))))))

;ans
(define (adjoin-set x set)
  (cond ((null? set) (list x))
        ((= x (car set)) set)
        ((< x (car set)) (cons x set))
        (else (cons (car set) (adjoin-set x (cdr set))))))
;これも平均のステップ数がn/2となる

gosh> (adjoin-set 100 '(1 2 3))
(1 2 3 100)
gosh> (adjoin-set 100 '(1 50 1000))
(1 50 100 1000)
gosh> (adjoin-set 20 '(1 50 1000))
(1 20 50 1000)
gosh> (adjoin-set 0 '(1 50 1000))
(0 1 50 1000)
gosh> (adjoin-set 0 '())
(0)
gosh> (adjoin-set 50 '(1 50 1000))
(1 50 1000)
