(use srfi-27)

(define (average x y)
  (/ (+ x y) 2.0))

(define (make-segment x1 y1 x2 y2)
  (cons (cons x1 y1) (cons x2 y2)))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (midpoint-segment segment)
  (cons (average (x-point (start-segment segment))
				 (x-point (end-segment segment)))
		(average (y-point (start-segment segment))
				 (y-point (end-segment segment)))))

(define (make-square width height)
  (cons width height))
(define (width-square square)
  (car square))
(define (height-square square)
  (cdr square))

(define (square-length square)
  (+ (* (width-square square) 2) (* (height-square square) 2)))
(define (square-area square)
  (* (width-square square) (height-square square) ))

(define (print-square square)
  (newline)
  (display (width-square square))
  (display "*")
  (display (height-square square))
  (newline))

(define sample-square (make-square 2 3))
(print-square sample-square) 
(print (square-length sample-square)) 
(print (square-area sample-square)) 
