(define (even? x)
    (= (remainder x 2) 0))
(define (sum term a next b)
    (if (> a b)
        0
        (+ (term a)
            (sum term (next a) next b))))
(define (integral f a b n)
    (define h (/ (- b a) n))
    (define (inc x)
        (+ x 1))
    (define (y k)
        (f (+ a (* k h))))
    (define (term k)
        (* (if (even? k) 2 4)
            (y k)))
    (* (/ h 3.0)
        (+ (y 0)
            (y n)
            (sum term 1 inc (- n 1)))))
(define (f x) x)
(define (cube x) (* x x x))

(print (integral f 0 1 500))
(print (integral cube 0 1 1000))
